language: julia
os:
    - osx
    - linux
julia:
    - 0.5
    - 0.6
    - nightly
notifications:
    email: false
# Avoids a Travis bug involving shallow clones
git:
    depth: 999999
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone("https://github.com/staticfloat/BinaryProvider.jl")'
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Nettle"); Pkg.test("Nettle"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("Nettle")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
